### PR TITLE
Adding django3.2 in tox.

### PR DESCRIPTION
**Pull request by awais786**
Adding django3.2 in tox.
Fixing warnings.

### CODE REVIEW

**Comment by richardbarran** [comment]
Hi - a suggestion: Django 3.0 is no longer supported. Can you update the PR to remove testing of that version?

**Comment by clintonb** [comment]
@richardbarran deprecation should happen in a separate commit and new major version. 

@awais786 sorry I missed this.

**Comment by richardbarran** [comment]
@clintonb ok.
Do you have the permissions/authority to make a new release of this package? It would be nice to have a new version with "works with Django 3.2" in the changelog.

**Comment by clintonb** [comment]
@richardbarran yep. I can work on that later today.

**Pull request merged**
