### PR TITLE
Fixed JS error in admin widget when zero elements

### PR DESCRIPTION
**Pull request by nemesisdesign**
This patch fixes an issue with the admin widget, which generates a javascript error when no m2m relations are present yet.

### CODE REVIEW

**Comment by nemesisdesign** [comment]
@gregmuellegger please could you take a look at this when you can? Thanks

**Comment by nemesisdesign** [comment]
@gregmuellegger any news?

**Comment by rohithasrk** [comment]
@gregmuellegger Can you please merge it? :D

**Comment by nemesisdesign** [comment]
@clintonb please can you review this PR?

The widget generates a JS error when there are zero elements and this PR fixes that.

**Comment by nemesisdesign** [comment]
Thanks a lot @clintonb

**Pull request merged**
