### PR TITLE
 Add Django 2.0 to 2.2 compatibility; Drop Django < 1.11 compatibility

### PR DESCRIPTION
**Pull request by joehybird**
- Huge code cleanup. Remove all compatibility functions for oldest Django releases.
- Add *real* support of through_defaults for Django >= 2.2

### CODE REVIEW

**Comment by joehybird** [comment]
cf: #130

**Comment by clintonb** [comment]
@joehybird I'm willing to review this if you are willing to make some changes. First up is rebasing since I just merged #136 to drop support for older versions of Django and Python. Also, note that the project has been moved to Jazzband.

**Comment by filipweidemann** [comment]
Any updates on this?

**Comment by Collederas** [comment]
Is there anything I can do to help out with merging this feature?

**Comment by richardbarran** [comment]
Closing as superseded by #142.

**Pull request closed without merging**
