### PR TITLE
adding full django2.0 compatibility.

### PR DESCRIPTION
**Pull request by gandhi23**
adding full django2.0 compatibility by adding django2.0 test to .travis.yml and tox.ini, so full django2.0 is implemented. this is a part of my Google code in task of @openwisp oraganisation. link of google code-in task: https://codein.withgoogle.com/dashboard/task-instances/4641906212470784/

### CODE REVIEW

**Comment by gandhi23** [comment]
@auvipy, i changed what u said in #119, except for that changing 1.11a1 to 1.111(it didn't work bro, for refernce see my previous PR, where u commented). i created this one bcz i accidentally deleted that branch.

**Comment by gandhi23** [comment]
@gregmuellegger , is this ok?

**Comment by nemesisdesign** [comment]
@gregmuellegger this patch may be save you some work ;-)

**Comment by vThaian** [comment]
Any chance to finish and merge this PR?

**Comment by richardbarran** [comment]
Closing as superseded by #142.

**Pull request closed without merging**
